name: "Pull Request Workflow"

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  staging:
    uses: ./.github/workflows/eas-build.yml
    with:
      environment: staging
      profile: preview
      platform: android
      submit: false
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      DOTENV_KEY_STAGING: ${{ secrets.DOTENV_KEY_STAGING }}
      DOTENV_ME: ${{ secrets.DOTENV_ME }}
